# Generated by Django 5.0.4 on 2025-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branch_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
